name: myfrontend
description: "A production-ready Flutter application"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9
  go_router: ^13.1.0
  http: ^1.2.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_dotenv: ^5.1.0
  flutter_secure_storage: ^8.0.0
  provider: ^6.0.5
  image_picker: ^1.0.4
  path: ^1.8.3

  # Add your other dependencies here

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2
  flutter_gen_runner: ^5.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/backG.png
    - assets/images/default.png
    - .env
